services:
  tomcat:
    image: tomcat:10.1-jdk17
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./target/ROOT:/usr/local/tomcat/webapps/ROOT
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tal3dem
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
