services:
  tomcat:
    image: tomcat:10.1-jdk17
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./target/ROOT:/usr/local/tomcat/webapps/ROOT
      - ./.env:/usr/local/tomcat/webapps/ROOT/.env
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_URL: ${DB_URL}
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
